#ifndef ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_SERVICE_HEALTH_LOCKER_HEALTH_LOCKER_H
#define ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_SERVICE_HEALTH_LOCKER_HEALTH_LOCKER_H

class HealthLocker {
public:
    static HealthLocker &getInstance();

    bool callback();
};

#endif //ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_SERVICE_HEALTH_LOCKER_HEALTH_LOCKER_H
