#ifndef ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_HEALTH_INTERFACE_H
#define ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_HEALTH_INTERFACE_H

class PlayerHealthInterface {
public:
    virtual float getHealth() = 0;

    virtual void setHealth(float health) = 0;
};

#endif //ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_HEALTH_INTERFACE_H
