#ifndef ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_ARMOR_INTERFACE_H
#define ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_ARMOR_INTERFACE_H

class PlayerArmorInterface {
public:
    virtual float getArmor() = 0;

    virtual void setArmor(float armor) = 0;
};

#endif //ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_INTERFACE_PLAYER_ARMOR_INTERFACE_H
