#ifndef ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_MENU_H
#define ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_MENU_H

class Menu {
public:
    static Menu &getInstance();

    void show();
};

#endif //ASSAULT_CUBE_HACKING_SRC_GAME_ASSAULT_CUBE_MENU_H
